title: "YouTube Video Category Classification based on Title and Description"
author: "Syahrul Hamdani"
copyright: "2021 Bitlabs Academy"
logo: ""
only_build_toc_files: true

parse:
  myst_enable_extensions:
    - deflist

execute:
  exclude_patterns:
    - 'modelling'
  timeout: 300

# references
bibtex_bibfiles:
  - references.bib

# sphinx configuration
sphinx:
  config:
    bibtex_reference_style: author_year
